---
title: "hw04-kanak-garg"
author: "Kanak Garg"
date: "4/9/2018"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, error = TRUE, fig.path = '../images/')
```

#Archives
```{r}
source("../code/archive-functions.R")
raw_data <- read_archive('stringr')
clean_data <- clean_archive(raw_data)
plot_archive(clean_data)
write.csv(clean_data, "../data/stringr-archive.csv")
```

```{r}
rd_ggplot <- read_archive('ggplot2')
cd_ggplot <- clean_archive(rd_ggplot)
write.csv(cd_ggplot, "../data/ggplot2-archive.csv")
rd_xml <- read_archive('XML')
cd_xml <- clean_archive(rd_xml)
write.csv(cd_xml, "../data/xml-archive.csv")
rd_knitr <- read_archive('knitr')
cd_knitr <- clean_archive(rd_knitr)
write.csv(cd_knitr, "../data/knitr-archive.csv")
rd_dplyr <- read_archive('dplyr')
cd_dplyr <- clean_archive(rd_dplyr)
write.csv(cd_dplyr, "../data/dplyr-archive.csv")
```


```{r}
newD <- rbind(cd_dplyr, cd_ggplot, cd_knitr, cd_xml)
ggplot(newD, aes(x = date, y = size, color = name)) +
  labs(y = 'Size (kilobytes)', x = 'Date') +
  geom_step()

ggplot(newD, aes(x = date, y = size, color = name)) +
  geom_step() + 
  labs(y = 'Size (kilobytes)', x = 'Date') + 
  facet_wrap(~ name, scales = 'free')
```

#Regex Functions
```{r}
source("../code/regex-functions.R")
split_chars('Go Bears!')
split_chars('Expecto Patronum')
vec <- c('G', 'o', ' ', 'B', 'e', 'a', 'r', 's', '!') 
num_vowels(vec)
count_vowels("The quick brown fox jumps over the lazy dog")
count_vowels("THE QUICK BROWN FOX JUMPS OVER THE LAZY DOG")
reverse_chars("gattaca")
reverse_chars("Lumox Maxima")
reverse_words("sentence! this reverse")
reverse_words("string")
```


#Data “Emotion in Text”


```{r}
content = read.csv("../data/text-emotion.csv", stringsAsFactors = F)$content

```
3.1) Number of characters per tweet
```{r}
counts = nchar(content)
print(summary(counts))
hist(counts, breaks = seq(0, max(counts)+5, by=5))
```


3.2) Number of Mentions
```{r}
mts = 1:length(content)
for (i in mts) {
  mts[i] = sum(grepl("^[^@@]*@[A-Za-z0-9_]{1,15}$", str_split(content[i], " ")[[1]]))
}
mts = unlist(mts)
mCounts = table(mts)
barplot(mCounts)
mCounts
content[mts == 10]
```

3.3) Hashtags



```{r}

hashtags = 1:length(content)
hashtagLengths = rep(0,max(counts))

for (i in hashtags) {
  tweetWords = str_split(content[i], " ")[[1]]
  whichTags = grep("#[A-Za-z][A-Za-z0-9]*", tweetWords, val = T)
  
  lengthIndices = nchar(whichTags) - 1
  hashtagLengths[lengthIndices] = hashtagLengths[lengthIndices] + 1
  hashtags[i] = length(whichTags)
}

names(hashtagLengths) <- 1:length(hashtagLengths)
hashtagLengths <- hashtagLengths[hashtagLengths > 0]
hashtags = unlist(hashtags)
hashCounts = table(hashtags)

hashCounts
barplot(hashCounts)
sum(hashtagLengths*as.numeric(names(hashtagLengths))/sum(hashtagLengths))
names(hashtagLengths[hashtagLengths == max(hashtagLengths)])

```
Avg = 7.963592
Mode = 4
